### ISSUE TITLE
readme on this repo not up to date (changelog)

### ISSUE THREAD

**Issue by schreibe** [atecon/scatterplot_matrix#1]
Hi Artur, the readme here still talks about the initial version 0.5, while in reality you're at 0.9.

**Comment by atecon** [comment]
Hi Sven, I am not sure what you mean. Version 0.5 was the initial version and the 0.9 the current (before the update today).

**Comment by schreibe** [comment]
I mean that the Changelog section of the readme only mentions 0.5, not 0.9. (Don't know whether any of the real content there is obsolete.)

**Comment by atecon** [comment]
Version 0.95 includes an improved help using the markdown format now.
