### ISSUE TITLE
nothing shown...

### ISSUE THREAD

**Issue by schreibe** [atecon/scatterplot_matrix#3]
Copying this report from internal email in March 2023:
Using the dataset data4-10.gdt from Ramanathan, and defining list L with ENROLL, CATHOL, PUPIL, WHITE, I'm executing the package's GUI -- the package dialog window is closed but nothing seems to happen.

**Comment by atecon** [comment]
Hi Sven,

This is confirmed here using both the GUI and a script file, respectively.

~~~
clear
set verbose off
open data4-10.gdt -q
list y = ENROLL CATHOL #PUPIL #WHITE
PairPlot(y)
~~~

Not sure for the issue is. I need to have a look in detail at this.

Artur

**Comment by schreibe** [comment]
Hi Artur, I'd like to get this package update done, so I played around with this problem some more, and I have some more evidence. It seems to me that it only fails if a series whose name starts with 'e' (or 'E') is _not_ in the last position in the list. Example:
```
include PairPlot.gfn
nulldata 20

series whatever = normal()

# Works:
series notstartingwith_e = normal()
list y = notstartingwith_e whatever
PairPlot(y)

# Works
series en = normal()
y = whatever en # notice en is at the end
PairPlot(y) 

# Fails:
list y = en whatever # en comes before the end
PairPlot(y)
```
This is of course not a solution, but maybe it's a step forward. In any case, this is very weird - does it ring any bell for you?

**Comment by atecon** [comment]
Version 0.95 fixes those problems. I close the ticket.
